import { useAuth } from "@/_core/hooks/useAuth";
import { CampusFixBrand } from "@/components/CampusFixBrand";
import { formatDate, PriorityPill, StatusPill } from "@/components/ComplaintBadges";
import DashboardLayout from "@/components/DashboardLayout";
import { NotificationMenu } from "@/components/NotificationMenu";
import { Button } from "@/components/ui/button";
import { complaintCategories, complaintCategoryNames } from "@/lib/complaintCategories";
import { trpc } from "@/lib/trpc";
import { ArrowRight, CircleAlert, ClipboardList, Clock3, Filter, Plus, Sparkles } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { Link, useLocation } from "wouter";

type StatusFilter = "All" | "Active" | "Resolved";

export default function Dashboard() {
  const { user } = useAuth();
  const [, setLocation] = useLocation();
  const profile = trpc.profile.me.useQuery(undefined, { enabled: Boolean(user) });
  const pendingStaff = profile.data?.role === "staff" && profile.data.staffApprovalStatus !== "approved";
  const complaints = trpc.complaints.mine.useQuery(undefined, { enabled: Boolean(user) && (user?.role === "admin" || Boolean(profile.data) && !pendingStaff), refetchInterval: 15_000 });
  const [categoryFilter, setCategoryFilter] = useState("All");
  const [statusFilter, setStatusFilter] = useState<StatusFilter>("All");
  useEffect(() => { if (user && user.role !== "admin" && !profile.isLoading && !profile.isError && !profile.data) setLocation("/onboarding"); if (pendingStaff) setLocation("/staff-approval"); }, [user, profile.isLoading, profile.isError, profile.data, pendingStaff, setLocation]);
  const openCount = complaints.data?.filter(item => item.status !== "Resolved").length ?? 0;
  const resolvedCount = complaints.data?.filter(item => item.status === "Resolved").length ?? 0;
  const filteredComplaints = useMemo(() => (complaints.data ?? []).filter(item => {
    const hasCategory = categoryFilter === "All" || item.departmentCategory === categoryFilter;
    const hasStatus = statusFilter === "All" || (statusFilter === "Active" ? item.status !== "Resolved" : item.status === "Resolved");
    return hasCategory && hasStatus;
  }), [complaints.data, categoryFilter, statusFilter]);
  const startComplaint = (category?: string) => { if (category) sessionStorage.setItem("campusfix-selected-category", category); setLocation("/file-complaint"); };

  return <DashboardLayout><div className="mx-auto max-w-6xl py-2 sm:py-5"><div className="flex flex-col gap-5 border-b border-slate-100 pb-6 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-bold text-blue-700">{user?.role === "admin" ? "Administrator workspace" : profile.data?.role === "staff" ? "Staff workspace" : "Student workspace"}</p><h1 className="mt-1 text-3xl font-extrabold tracking-[-0.05em] text-slate-950">Good to see you{user?.name ? `, ${user.name.split(" ")[0]}` : ""}.</h1><p className="mt-2 text-sm text-slate-500">File a complaint, follow every update, and help make campus better.</p></div><div className="flex items-center gap-2"><NotificationMenu /><Button onClick={() => startComplaint()} className="rounded-xl bg-[#0b57d0] font-bold hover:bg-[#0848af]"><Plus className="mr-1.5 h-4 w-4" /> File a complaint</Button></div></div>
    {profile.isError && user?.role !== "admin" && <div className="mt-5 flex flex-wrap items-center justify-between gap-3 rounded-xl border border-amber-100 bg-amber-50 px-4 py-3 text-sm text-amber-900"><span>We could not load all of your profile details just now.</span><Button variant="ghost" onClick={() => profile.refetch()} className="h-8 font-bold text-amber-800 hover:bg-amber-100">Try again</Button></div>}
    <section className="relative mt-7 overflow-hidden rounded-[1.65rem] border-2 border-[#ffd43b]/70 bg-[#082962] text-white shadow-[0_22px_44px_rgba(7,42,99,0.20)]"><div className="absolute -left-10 -top-14 h-44 w-44 rounded-full border-[24px] border-white/5" /><div className="grid gap-5 p-6 sm:p-7 lg:grid-cols-[0.72fr_1.28fr] lg:items-center"><div className="relative"><span className="grid h-12 w-12 place-items-center rounded-xl bg-[#ffd43b] text-[#082962] shadow-lg shadow-black/15"><ClipboardList className="h-6 w-6" /></span><p className="mt-5 text-xs font-extrabold uppercase tracking-[0.16em] text-[#ffd43b]">Student complaint desk</p><h2 className="mt-2 text-3xl font-extrabold tracking-[-0.04em]">Raise a complaint. Get it moving.</h2><p className="mt-3 text-sm leading-relaxed text-blue-100">Choose the issue type below and CampusFix will guide you through location, evidence, AI review, and tracking.</p><Button onClick={() => startComplaint()} size="lg" className="mt-5 rounded-xl bg-[#ffd43b] px-6 text-base font-extrabold text-[#082962] shadow-lg shadow-black/15 hover:bg-[#ffc91f]">Raise a complaint <ArrowRight className="ml-2 h-4 w-4" /></Button></div><div className="relative grid gap-2 sm:grid-cols-2 xl:grid-cols-3">{complaintCategories.map(category => { const Icon = category.icon; return <button key={category.name} type="button" onClick={() => startComplaint(category.name)} className="group flex min-h-[82px] items-start gap-3 rounded-xl border border-white/10 bg-white/[0.07] p-3 text-left transition-all hover:-translate-y-0.5 hover:bg-white/[0.13] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#ffd43b]"><span className={`grid h-8 w-8 shrink-0 place-items-center rounded-lg ${category.tone}`}><Icon className="h-4 w-4" /></span><span><span className="block text-sm font-extrabold text-white">{category.name}</span><span className="mt-1 block text-xs leading-snug text-blue-100">{category.description}</span></span></button>; })}</div></div></section>
    <div className="mt-7 grid gap-4 sm:grid-cols-3"><Metric icon={ClipboardList} label="Total reports" value={complaints.data?.length ?? 0} tone="blue" /><Metric icon={Clock3} label="Active tickets" value={openCount} tone="amber" /><Metric icon={Sparkles} label="Resolved" value={resolvedCount} tone="emerald" /></div>
    <section className="mt-8"><div className="mb-4 flex flex-col gap-4 xl:flex-row xl:items-end xl:justify-between"><div><h2 className="text-lg font-extrabold text-slate-950">Your complaints</h2><p className="mt-0.5 text-sm text-slate-500">View your category, priority, status, evidence, and complete ticket timeline.</p></div><div className="flex flex-wrap items-center gap-2"><span className="inline-flex items-center gap-1.5 text-xs font-bold text-slate-500"><Filter className="h-3.5 w-3.5" /> Filter</span><select aria-label="Filter by category" value={categoryFilter} onChange={event => setCategoryFilter(event.target.value)} className="h-9 rounded-lg border border-slate-200 bg-white px-2.5 text-sm font-semibold text-slate-700 shadow-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-500"><option value="All">All categories</option>{complaintCategoryNames.map(category => <option key={category} value={category}>{category}</option>)}</select>{(["All", "Active", "Resolved"] as StatusFilter[]).map(filter => <button type="button" key={filter} onClick={() => setStatusFilter(filter)} className={`rounded-lg px-3 py-2 text-xs font-bold transition-colors ${statusFilter === filter ? "bg-blue-700 text-white" : "bg-white text-slate-600 ring-1 ring-inset ring-slate-200 hover:bg-slate-50"}`}>{filter}</button>)}</div></div>
      <div className="overflow-hidden rounded-2xl border border-slate-100 bg-white shadow-[0_12px_30px_rgba(14,54,114,0.06)]">{complaints.isLoading && <div className="p-8 text-sm text-slate-500">Loading your reports…</div>}{complaints.isError && <div className="p-8 text-center"><p className="font-bold text-slate-800">Your reports could not be loaded.</p><p className="mt-1 text-sm text-slate-500">Please check your connection and try again.</p><Button variant="outline" onClick={() => complaints.refetch()} className="mt-4 rounded-xl bg-white font-bold">Try again</Button></div>}{!complaints.isLoading && !complaints.isError && !complaints.data?.length && <EmptyReports onCreate={() => startComplaint()} />}{!complaints.isLoading && !complaints.isError && Boolean(complaints.data?.length) && !filteredComplaints.length && <div className="p-10 text-center"><Filter className="mx-auto h-6 w-6 text-slate-300" /><p className="mt-3 font-bold text-slate-700">No complaints match these filters.</p><Button variant="ghost" onClick={() => { setCategoryFilter("All"); setStatusFilter("All"); }} className="mt-2 font-bold text-blue-700">Clear filters</Button></div>}{filteredComplaints.map(item => <Link key={item.id} href={`/ticket/${item.id}`} className="block border-b border-slate-100 p-5 last:border-0 transition-colors hover:bg-blue-50/40"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><p className="font-extrabold text-slate-900">{item.departmentCategory}</p><StatusPill status={item.status} /></div><p className="mt-1 line-clamp-1 text-sm text-slate-500">{item.hostel}, Block {item.block}, Room {item.room}</p><p className="mt-2 font-mono text-xs font-semibold text-blue-700">{item.complaintId}</p></div><div className="flex items-center justify-between gap-4 sm:justify-end"><PriorityPill priority={item.priorityLevel} /><span className="text-xs font-medium text-slate-400">{formatDate(item.updatedAt)}</span><ArrowRight className="h-4 w-4 text-slate-400" /></div></div></Link>)}</div>
    </section>
    <section className="mt-8 overflow-hidden rounded-2xl bg-slate-100 p-6 sm:p-7"><div className="flex flex-col gap-6 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-start gap-4"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-white text-blue-700"><CircleAlert className="h-5 w-5" /></span><div><h2 className="font-extrabold text-slate-950">Your student workspace keeps you informed.</h2><p className="mt-1 max-w-xl text-sm leading-relaxed text-slate-600">You can file a complaint, attach evidence, see priority and category, open its full activity timeline, and receive every status update. Only administrators can change ticket status.</p></div></div><Button onClick={() => startComplaint()} className="rounded-xl bg-[#082962] font-bold hover:bg-[#061f4a]">File a complaint</Button></div></section>
  </div></DashboardLayout>;
}

function Metric({ icon: Icon, label, value, tone }: { icon: typeof ClipboardList; label: string; value: number; tone: "blue" | "amber" | "emerald" }) { const styles = { blue: "bg-blue-50 text-blue-700", amber: "bg-amber-50 text-amber-700", emerald: "bg-emerald-50 text-emerald-700" }; return <div className="rounded-2xl border border-slate-100 bg-white p-5 shadow-[0_10px_25px_rgba(14,54,114,0.04)]"><span className={`grid h-10 w-10 place-items-center rounded-xl ${styles[tone]}`}><Icon className="h-5 w-5" /></span><p className="mt-4 text-2xl font-extrabold tracking-tight text-slate-950">{value}</p><p className="mt-0.5 text-sm font-medium text-slate-500">{label}</p></div>; }
function EmptyReports({ onCreate }: { onCreate: () => void }) { return <div className="grid place-items-center px-5 py-14 text-center"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-blue-50 text-blue-700"><CampusFixBrand compact /></span><h3 className="mt-4 font-extrabold text-slate-900">No complaints yet</h3><p className="mt-1 max-w-sm text-sm leading-relaxed text-slate-500">Choose one of the campus categories above to file your first complaint and track each update.</p><Button onClick={onCreate} className="mt-5 rounded-xl bg-[#0b57d0] font-bold hover:bg-[#0848af]"><Plus className="mr-1.5 h-4 w-4" /> File a complaint</Button></div>; }
