import { useAuth } from "@/_core/hooks/useAuth";
import { CampusFixBrand } from "@/components/CampusFixBrand";
import { Button } from "@/components/ui/button";
import { startLogin } from "@/const";
import { ArrowRight, BrainCircuit, CheckCircle2, ClipboardCheck, Clock3, Menu, ShieldCheck, Sparkles, Wrench } from "lucide-react";
import React, { useState } from "react";
import { useLocation } from "wouter";

const features = [
  { icon: ClipboardCheck, title: "Report in minutes", copy: "Capture the issue, exact location, and optional supporting evidence in one guided flow." },
  { icon: BrainCircuit, title: "Smart routing", copy: "AI prepares a concise analysis and directs each complaint to the right campus department." },
  { icon: Clock3, title: "Track every step", copy: "Follow each ticket from submission through check-in, progress, and resolution." },
  { icon: ShieldCheck, title: "Clear accountability", copy: "Role-aware access and a visible ticket history keep every update easy to understand." },
];

export default function Home() {
  const { isAuthenticated, user } = useAuth();
  const [, setLocation] = useLocation();
  const [menuOpen, setMenuOpen] = useState(false);
  const openStudentFiling = () => setLocation("/file-complaint");
  const openAdmin = () => isAuthenticated ? setLocation("/admin") : startLogin();

  return <div className="min-h-screen overflow-hidden bg-[#f9fbff] text-slate-900">
    <header className="relative z-30 mx-auto flex max-w-7xl items-center justify-between px-5 py-5 sm:px-8 lg:px-10"><CampusFixBrand /><nav className="hidden items-center gap-7 text-sm font-semibold text-slate-600 md:flex"><a href="#how-it-works" className="transition-colors hover:text-blue-700">How it works</a><a href="#features" className="transition-colors hover:text-blue-700">Features</a><a href="#privacy" className="transition-colors hover:text-blue-700">Privacy</a></nav><div className="hidden items-center gap-2 md:flex"><Button variant="outline" size="sm" onClick={openAdmin} className="h-8 rounded-lg border-slate-200 bg-white px-2.5 text-xs font-bold text-slate-600 hover:bg-slate-50 hover:text-slate-800"><ShieldCheck className="mr-1.5 h-3.5 w-3.5" />{isAuthenticated ? "Admin portal" : "Admin access"}</Button><Button onClick={openStudentFiling} className="rounded-xl bg-[#0b57d0] px-5 font-bold shadow-lg shadow-blue-700/15 hover:bg-[#0848af]">Raise a complaint<ArrowRight className="ml-2 h-4 w-4" /></Button></div><Button variant="ghost" size="icon" className="md:hidden" onClick={() => setMenuOpen(open => !open)} aria-label="Toggle menu"><Menu className="h-5 w-5" /></Button></header>
    {menuOpen && <div className="absolute inset-x-4 top-20 z-40 rounded-2xl border border-slate-100 bg-white p-4 shadow-xl md:hidden"><div className="flex flex-col gap-2"><a href="#how-it-works" onClick={() => setMenuOpen(false)} className="rounded-xl px-3 py-2 text-sm font-semibold">How it works</a><a href="#features" onClick={() => setMenuOpen(false)} className="rounded-xl px-3 py-2 text-sm font-semibold">Features</a><Button onClick={openStudentFiling} className="mt-2 bg-[#0b57d0] font-bold">Raise a complaint</Button><Button variant="outline" size="sm" onClick={openAdmin} className="mt-1 border-slate-200 text-xs font-bold"><ShieldCheck className="mr-1.5 h-3.5 w-3.5" />Admin access</Button></div></div>}
    <main><section className="relative isolate overflow-hidden"><div data-testid="campus-hero-background" className="absolute inset-0 -z-10 bg-cover bg-center bg-no-repeat" style={{ backgroundImage: "url('/manus-storage/campusfix-college-hero_cbf3beee.jpg')" }} /><div data-testid="campus-hero-overlay" className="absolute inset-0 -z-0 bg-gradient-to-r from-[#f9fbff]/95 via-[#f9fbff]/90 to-[#eff6ff]/76" /><section className="relative z-10 mx-auto grid max-w-7xl items-center gap-14 px-5 pb-20 pt-12 sm:px-8 sm:pb-28 lg:grid-cols-[1.05fr_0.95fr] lg:px-10 lg:pt-20"><div className="absolute left-[30%] top-0 -z-0 h-96 w-96 rounded-full bg-blue-100/60 blur-3xl" /><div className="relative z-10"><div className="inline-flex items-center gap-2 rounded-full border border-blue-100 bg-white px-3 py-1.5 text-xs font-bold text-blue-800 shadow-sm"><Sparkles className="h-3.5 w-3.5 text-[#f9be1b]" /> Student complaint desk</div><h1 className="mt-6 max-w-2xl text-5xl font-extrabold leading-[0.99] tracking-[-0.065em] text-[#071b42] sm:text-6xl lg:text-7xl">A better campus starts with <span className="text-[#0b57d0]">one clear report.</span></h1><p className="mt-6 max-w-xl text-lg leading-relaxed text-slate-600">Students can raise a complaint in minutes, add evidence, and follow every update through to resolution.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Button onClick={openStudentFiling} size="lg" className="h-13 rounded-xl bg-[#0b57d0] px-7 text-base font-extrabold shadow-xl shadow-blue-700/20 hover:bg-[#0848af]">Raise a complaint <ArrowRight className="ml-2 h-4 w-4" /></Button><Button onClick={() => document.getElementById("how-it-works")?.scrollIntoView({ behavior: "smooth" })} variant="outline" size="lg" className="h-12 rounded-xl border-slate-200 bg-white px-6 font-bold text-slate-700">See how it works</Button></div><p className="mt-3 text-xs font-semibold text-blue-700">Student filing is the fastest way to get the right campus team involved.</p><div className="mt-7 flex flex-wrap gap-x-6 gap-y-3 text-sm font-semibold text-slate-600"><span className="flex items-center gap-2"><CheckCircle2 className="h-4 w-4 text-emerald-600" /> Secure Manus OAuth access</span><span className="flex items-center gap-2"><CheckCircle2 className="h-4 w-4 text-emerald-600" /> AI-assisted routing</span></div></div>
      <div className="relative z-10 mx-auto w-full max-w-[510px]"><div className="absolute -right-8 top-8 h-28 w-28 rounded-[2rem] bg-[#ffd43b] opacity-90 sm:-right-16" /><div className="absolute -bottom-10 -left-4 h-36 w-36 rounded-full border-[18px] border-blue-200/80" /><div className="relative rounded-[2.2rem] border border-white bg-white p-4 shadow-[0_28px_70px_rgba(13,53,111,0.16)] sm:p-5"><div className="flex items-center justify-between border-b border-slate-100 px-2 pb-4"><CampusFixBrand compact /><span className="rounded-full bg-blue-50 px-2.5 py-1 text-xs font-bold text-blue-700">Student filing</span></div><div className="px-2 pt-5"><p className="text-xs font-bold uppercase tracking-[0.15em] text-blue-700">Start with the right issue type</p><h2 className="mt-1 text-2xl font-extrabold tracking-tight text-slate-950">Tell campus what needs attention.</h2><p className="mt-2 text-sm leading-relaxed text-slate-500">Choose a category, describe the problem, and optionally add evidence.</p><div className="mt-5 grid gap-3 sm:grid-cols-3"><div className="rounded-2xl bg-amber-50 p-4"><Wrench className="h-5 w-5 text-amber-700" /><p className="mt-6 text-sm font-extrabold text-amber-950">Electrical</p><p className="mt-1 text-xs leading-relaxed text-amber-800">Lights, fans, and power</p></div><div className="rounded-2xl bg-blue-50 p-4"><BrainCircuit className="h-5 w-5 text-blue-700" /><p className="mt-6 text-sm font-extrabold text-blue-950">Smart routing</p><p className="mt-1 text-xs leading-relaxed text-blue-800">AI reviews each report</p></div><div className="rounded-2xl bg-violet-50 p-4"><ClipboardCheck className="h-5 w-5 text-violet-700" /><p className="mt-6 text-sm font-extrabold text-violet-950">Evidence</p><p className="mt-1 text-xs leading-relaxed text-violet-800">Photos and documents</p></div></div><Button onClick={openStudentFiling} className="mt-4 w-full rounded-xl bg-[#082962] font-bold hover:bg-[#061f4a]">Start a complaint <ArrowRight className="ml-2 h-4 w-4" /></Button></div></div></div>
    </section></section>
    <section id="features" className="border-y border-blue-100/60 bg-white py-20"><div className="mx-auto max-w-7xl px-5 sm:px-8 lg:px-10"><div className="max-w-2xl"><p className="text-xs font-bold uppercase tracking-[0.18em] text-blue-700">Made for campus life</p><h2 className="mt-3 text-3xl font-extrabold tracking-[-0.045em] text-[#071b42] sm:text-4xl">Every report gets a clearer path to resolution.</h2></div><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{features.map(({ icon: Icon, title, copy }) => <article key={title} className="group rounded-2xl border border-slate-100 bg-[#fbfcff] p-6 transition-all duration-200 hover:-translate-y-1 hover:border-blue-100 hover:bg-white hover:shadow-[0_18px_36px_rgba(25,70,138,0.08)]"><span className="grid h-11 w-11 place-items-center rounded-xl bg-blue-50 text-blue-700"><Icon className="h-5 w-5" /></span><h3 className="mt-5 font-extrabold text-slate-900">{title}</h3><p className="mt-2 text-sm leading-relaxed text-slate-600">{copy}</p></article>)}</div></div></section>
    <section id="how-it-works" className="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:px-10"><div className="grid gap-10 lg:grid-cols-[0.75fr_1.25fr]"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-blue-700">How it works</p><h2 className="mt-3 text-3xl font-extrabold tracking-[-0.045em] text-[#071b42] sm:text-4xl">Report · Track · Resolve</h2><p className="mt-4 max-w-sm leading-relaxed text-slate-600">A purposeful workflow keeps the user informed from the first report to the final resolution.</p></div><div className="grid gap-4 sm:grid-cols-3">{[["01", "Report", "Describe the issue, add the precise location, and include optional evidence."], ["02", "Track", "Review AI routing and follow updates as the right team takes action."], ["03", "Resolve", "Get notified at each stage and keep a complete ticket history."]].map(([number, title, copy]) => <div key={number} className="rounded-2xl bg-[#082962] p-6 text-white"><p className="text-4xl font-extrabold tracking-[-0.05em] text-[#ffd43b]">{number}</p><h3 className="mt-10 text-xl font-bold">{title}</h3><p className="mt-2 text-sm leading-relaxed text-blue-100">{copy}</p></div>)}</div></div></section>
    <section id="privacy" className="mx-5 mb-5 rounded-[2rem] bg-[#082962] px-6 py-12 text-white sm:mx-8 sm:px-10 lg:mx-auto lg:max-w-7xl"><div className="flex flex-col justify-between gap-8 md:flex-row md:items-center"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-blue-200">Designed with trust in mind</p><h2 className="mt-3 max-w-2xl text-3xl font-extrabold tracking-[-0.045em]">A smarter, cleaner, more responsive campus.</h2><p className="mt-3 max-w-xl text-blue-100">Role-aware workspaces, secure uploads, clear status updates, and auditable activity help everyone act with confidence.</p></div><Button onClick={openStudentFiling} size="lg" className="shrink-0 rounded-xl bg-[#ffd43b] px-6 font-extrabold text-[#082962] hover:bg-[#ffc91f]">Raise a complaint <ArrowRight className="ml-2 h-4 w-4" /></Button></div></section>
    </main><footer className="mx-auto flex max-w-7xl flex-col gap-3 px-5 py-8 text-sm text-slate-500 sm:flex-row sm:items-center sm:justify-between sm:px-8 lg:px-10"><CampusFixBrand compact /><span>CampusFix · Report · Track · Resolve</span></footer>
  </div>;
}
