import DashboardLayout from "@/components/DashboardLayout";
import { formatDate, PriorityPill, StatusPill } from "@/components/ComplaintBadges";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { ArrowLeft, Check, ClipboardCheck, FileText, MapPin, RefreshCw, Wrench } from "lucide-react";
import { useRoute } from "wouter";
import { useLocation } from "wouter";

const stages = ["Pending", "Checked In", "In Progress", "Resolved"];

export default function Ticket({ confirmation = false }: { confirmation?: boolean }) {
  const [, params] = useRoute(confirmation ? "/confirmed/:id" : "/ticket/:id");
  const [, setLocation] = useLocation();
  const id = Number(params?.id);
  const detail = trpc.complaints.detail.useQuery({ complaintId: id }, { enabled: Number.isInteger(id) && id > 0, refetchInterval: 15_000 });
  const ticket = detail.data?.complaint;
  if (detail.isError || (!detail.isLoading && !ticket)) return <DashboardLayout><div className="mx-auto grid min-h-[60vh] max-w-lg place-items-center px-5 text-center"><div><span className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-rose-50 text-rose-600"><ClipboardCheck className="h-7 w-7" /></span><h1 className="mt-5 text-2xl font-extrabold text-slate-950">This ticket is unavailable</h1><p className="mt-2 text-sm leading-relaxed text-slate-500">{detail.error?.message ?? "The ticket may no longer exist, or you may not have permission to view it."}</p><div className="mt-5 flex justify-center gap-3"><Button variant="outline" onClick={() => setLocation("/dashboard")} className="rounded-xl bg-white font-bold">Back to workspace</Button><Button onClick={() => detail.refetch()} className="rounded-xl bg-[#0b57d0] font-bold hover:bg-[#0848af]"><RefreshCw className="mr-2 h-4 w-4" /> Try again</Button></div></div></div></DashboardLayout>;
  return <DashboardLayout><div className="mx-auto max-w-5xl py-2 sm:py-5">{detail.isLoading && <div className="p-8 text-sm text-slate-500">Loading ticket…</div>}{ticket && <><div className="flex items-start justify-between gap-4"><div className="flex items-start gap-3"><Button variant="ghost" size="icon" onClick={() => setLocation("/dashboard")} className="mt-0.5 rounded-xl"><ArrowLeft className="h-5 w-5" /></Button><div>{confirmation ? <p className="text-sm font-bold text-emerald-700">Complaint submitted successfully</p> : <p className="text-sm font-bold text-blue-700">Complaint tracking</p>}<h1 className="mt-1 text-3xl font-extrabold tracking-[-0.05em] text-slate-950">{ticket.complaintId}</h1><p className="mt-1 text-sm text-slate-500">Created {formatDate(ticket.createdAt)} · ticket details refresh automatically.</p></div></div><Button onClick={() => detail.refetch()} variant="outline" className="hidden rounded-xl border-slate-200 bg-white font-bold sm:flex"><RefreshCw className="mr-2 h-4 w-4" /> Refresh</Button></div>
    {confirmation && <div className="mt-7 flex items-start gap-3 rounded-2xl border border-emerald-100 bg-emerald-50 p-5 text-emerald-950"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-emerald-600 text-white"><Check className="h-5 w-5" /></span><div><p className="font-extrabold">Your complaint is now with the right team.</p><p className="mt-1 text-sm leading-relaxed text-emerald-800">Keep this ticket ID handy. CampusFix will show each status change here and in your notifications.</p></div></div>}
    <div className="mt-7 grid gap-6 lg:grid-cols-[1.2fr_0.8fr]"><section className="space-y-6"><div className="rounded-2xl border border-slate-100 bg-white p-5 shadow-[0_12px_30px_rgba(14,54,114,0.06)] sm:p-7"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[0.15em] text-slate-500">Assigned department</p><h2 className="mt-1 text-2xl font-extrabold tracking-tight text-slate-950">{ticket.departmentCategory}</h2></div><div className="flex items-center gap-2"><PriorityPill priority={ticket.priorityLevel} /><StatusPill status={ticket.status} /></div></div><div className="mt-6 grid gap-4 border-t border-slate-100 pt-5 sm:grid-cols-2"><div className="flex gap-3"><MapPin className="mt-0.5 h-5 w-5 shrink-0 text-blue-700" /><div><p className="text-xs font-bold uppercase tracking-[0.12em] text-slate-500">Location</p><p className="mt-1 text-sm font-semibold text-slate-700">{ticket.hostel}, Block {ticket.block}, Room {ticket.room}</p></div></div><div className="flex gap-3"><ClipboardCheck className="mt-0.5 h-5 w-5 shrink-0 text-blue-700" /><div><p className="text-xs font-bold uppercase tracking-[0.12em] text-slate-500">Original report</p><p className="mt-1 text-sm leading-relaxed text-slate-700">{ticket.description}</p></div></div></div><div className="mt-5 rounded-xl bg-slate-50 p-4"><p className="text-xs font-bold uppercase tracking-[0.13em] text-slate-500">AI summary</p><p className="mt-2 text-sm leading-relaxed text-slate-700">{ticket.aiSummary}</p></div></div>
        <div className="rounded-2xl border border-slate-100 bg-white p-5 shadow-[0_12px_30px_rgba(14,54,114,0.06)] sm:p-7"><h2 className="font-extrabold text-slate-950">Ticket timeline</h2><div className="mt-5 space-y-0">{stages.map((stage, index) => { const reached = stages.indexOf(ticket.status) >= index; const event = detail.data?.activity.find(item => item.eventType === "status_changed" && item.message.includes(stage)) ?? (stage === "Pending" ? detail.data?.activity.find(item => item.eventType === "submitted") : undefined); return <div key={stage} className="flex gap-4"><div className="flex flex-col items-center"><span className={`grid h-7 w-7 place-items-center rounded-full text-xs ${reached ? "bg-blue-700 text-white" : "bg-slate-100 text-slate-400"}`}>{reached ? <Check className="h-3.5 w-3.5" /> : index + 1}</span>{index < stages.length - 1 && <span className={`h-10 w-px ${reached ? "bg-blue-200" : "bg-slate-200"}`} />}</div><div className="pb-5"><p className={`text-sm font-bold ${reached ? "text-slate-900" : "text-slate-400"}`}>{stage}</p><p className="mt-0.5 text-sm text-slate-500">{event?.message ?? (reached ? "Ticket has reached this step." : "Waiting for the previous step.")}</p></div></div>; })}</div></div>
      </section><aside className="space-y-4"><div className="rounded-2xl bg-[#082962] p-6 text-white"><span className="grid h-10 w-10 place-items-center rounded-xl bg-white/10 text-[#ffd43b]"><Wrench className="h-5 w-5" /></span><h2 className="mt-5 font-extrabold">What happens next?</h2><p className="mt-2 text-sm leading-relaxed text-blue-100">The assigned department will review the report and update this ticket as work progresses.</p></div><div className="rounded-2xl border border-slate-100 bg-white p-5"><h2 className="font-extrabold text-slate-900">Supporting evidence</h2>{detail.data?.attachments.length ? <div className="mt-3 space-y-2">{detail.data.attachments.map(attachment => <a key={attachment.id} href={attachment.storageUrl} target="_blank" rel="noreferrer" className="flex items-center gap-3 rounded-xl bg-slate-50 p-3 text-sm font-semibold text-blue-700 hover:bg-blue-50"><FileText className="h-4 w-4" /> <span className="truncate">{attachment.fileName}</span></a>)}</div> : <p className="mt-2 text-sm text-slate-500">No photo or document was attached.</p>}</div></aside></div></>}</div></DashboardLayout>;
          <div className="rounded-2xl border border-slate-100 bg-white p-5"><h2 className="font-extrabold text-slate-900">Supporting evidence</h2>{detail.data?.attachments.length ? <div className="mt-3 space-y-2">{detail.data.attachments.map(attachment => <a key={attachment.id} href={attachment.storageUrl} download={attachment.fileName} target="_blank" rel="noreferrer" className="flex items-center gap-3 rounded-xl bg-slate-50 p-3 text-sm font-semibold text-blue-700 hover:bg-blue-50"><FileText className="h-4 w-4" /> <span className="truncate">{attachment.fileName}</span></a>)}</div> : <p className="mt-2 text-sm text-slate-500">No photo or document was attached.</p>}</div></aside></div></>}</div></DashboardLayout>;
}
